### ISSUE TITLE
Habitable zone plotting is broken

### ISSUE THREAD

**Issue by Nazine** [OpenExoplanetCatalogue/oec_web#10]
http://www.openexoplanetcatalogue.com/planet/Gliese%201214%20b/ <--- this planet is not in the habitable zone (obviously) but OEC still calculates to say so.

http://www.openexoplanetcatalogue.com/system.html?id=Gliese%20785%20b <--- gliese 785b is not in the habitable zone, gliese 785c is.

**Comment by hannorein** [comment]
You're right. This is indeed a bug. Thanks for posting.
