### ISSUE TITLE
Planet Size plot is broken (or out of order)

### ISSUE THREAD

**Issue by Nazine** [OpenExoplanetCatalogue/oec_web#12]
http://openexoplanetcatalogue.com/planet/Kepler-97%20c/

On Kepler 97-c's page, the planet size plot shows "Kepler 97-b" instead of Kepler-97-c.

**Comment by ziphead** [comment]
It's because, for Kepler-97 c,  there're no "radius" or "mass" tags with data in the system xml file. It has this tag <mass lowerlimit>
`		
<planet>
			<name>Kepler-97 c</name>
			<name>KOI-292.10</name>
			<name>KOI-292 c</name>
			<name>KIC 11075737 c</name>
			<period lowerlimit="789" />
			<list>Confirmed planets</list>
			<mass lowerlimit="1.082121" />
			<description>This planet has been discovered during a radial velocity follow up of stars observed by Kepler which host planet candidates. Although other planets in this system are transiting, this one is not.</description>
			<discoveryyear>2014</discoveryyear>
			<lastupdate>14/02/24</lastupdate>
			<discoverymethod>RV</discoverymethod>
		</planet>
`
