### ISSUE TITLE
OEC website error

### ISSUE THREAD

**Issue by ziphead** [OpenExoplanetCatalogue/oec_web#19]
http://www.openexoplanetcatalogue.com/systems/?filters=habitable   Habitable zone planets link leads to an internal server error 500.

**Comment by ziphead** [comment]
I think I found what causing this error. The problem is in <spectraltype>Pulsar</spectraltype> in PSR 1257+12.xml file . 
And your algorithm in oec_filters.py doesn't know anything about Pulsar spectral type.


```
    spectralTypeMain = getText(star,"./spectraltype","G")[0]

    if temperature is None:
        if spectralTypeMain=="O":
            temperature = 40000
        if spectralTypeMain=="B":
            temperature = 20000
        if spectralTypeMain=="A":
            temperature = 8500
        if spectralTypeMain=="F":
            temperature = 6500
        if spectralTypeMain=="G":
            temperature = 5500
        if spectralTypeMain=="K":
            temperature = 4000
        if spectralTypeMain=="M":
            temperature = 3000
        
    rel_temp = temperature - 5700.
```

**Comment by ziphead** [comment]
I'm not an astronomer, but I guess it is very unlikely that there is habitable zone near a pulsar or white dwarf. Hopefully, this commit can help

**Comment by hannorein** [comment]
Awesome. That fixed it! Thanks a lot.
