### ISSUE TITLE
Add "Habitable Zone" field in options

### ISSUE THREAD

**Issue by Karlon** [OpenExoplanetCatalogue/oec_web#9]
Any planet that is calculated to be in the habitable zone, should be marked as being in the habitable zone. So when a user ticks "Habitable zone" on the options at http://www.openexoplanetcatalogue.com/systems/ - he/she can get a list of the planets that are in the habitable zone. This is efficient and will be of extremely great use to extraterrestrial researchers.

**Comment by hannorein** [comment]
Added in 118672d27b9f19922addad238a12559b361fdb5d
